import React, { useState } from 'react';
import { StyleSheet, Text, View, TextInput, TouchableOpacity, FlatList, Alert, Modal } from 'react-native';

export default function App() {
  const [activeTab, setActiveTab] = useState('cari');

    const [customers, setCustomers] = useState([
        { id: '1', name: 'Engin abi', phone: '05434576828', balanceUSD: 118.00 },
          ]);

            const [stock, setStock] = useState([
                { id: '1', name: 'SAMSUNG A32 WF Süper OLED', qty: 5, priceUSD: 32.00 },
                  ]);

                    const [cariModalVisible, setCariModalVisible] = useState(false);
                      const [stokModalVisible, setStokModalVisible] = useState(false);

                        const [newCariName, setNewCariName] = useState('');
                          const [newCariPhone, setNewCariPhone] = useState('');
                            const [newStokName, setNewStokName] = useState('');
                              const [newStokQty, setNewStokQty] = useState('');
                                const [newStokPrice, setNewStokPrice] = useState('');

                                  const handleAddCari = () => {
                                      if (!newCariName) return Alert.alert('Hata', 'Müşteri adı giriniz.');
                                          setCustomers([...customers, { id: Date.now().toString(), name: newCariName, phone: newCariPhone, balanceUSD: 0 }]);
                                              setNewCariName(''); setNewCariPhone(''); setCariModalVisible(false);
                                                };

                                                  const handleAddStok = () => {
                                                      if (!newStokName || !newStokQty || !newStokPrice) return Alert.alert('Hata', 'Tüm alanları doldurunuz.');
                                                          setStock([...stock, { id: Date.now().toString(), name: newStokName, qty: parseInt(newStokQty) || 0, priceUSD: parseFloat(newStokPrice) || 0 }]);
                                                              setNewStokName(''); setNewStokQty(''); setNewStokPrice(''); setStokModalVisible(false);
                                                                };

                                                                  return (
                                                                      <View style={styles.container}>
                                                                            <View style={styles.header}>
                                                                                    <Text style={styles.headerTitle}>DUKKANAPP</Text>
                                                                                          </View>

                                                                                                <View style={styles.tabBar}>
                                                                                                        <TouchableOpacity style={[styles.tab, activeTab === 'cari' && styles.activeTab]} onPress={() => setActiveTab('cari')}>
                                                                                                                  <Text style={styles.tabText}>Cari Hesaplar</Text>
                                                                                                                          </TouchableOpacity>
                                                                                                                                  <TouchableOpacity style={[styles.tab, activeTab === 'stok' && styles.activeTab]} onPress={() => setActiveTab('stok')}>
                                                                                                                                            <Text style={styles.tabText}>Stok Yönetimi</Text>
                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                          </View>

                                                                                                                                                                {activeTab === 'cari' && (
                                                                                                                                                                        <View style={styles.content}>
                                                                                                                                                                                  <TouchableOpacity style={styles.addBtn} onPress={() => setCariModalVisible(true)}>
                                                                                                                                                                                              <Text style={styles.btnText}>+ Yeni Cari Ekle</Text>
                                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                                  <FlatList
                                                                                                                                                                                                                              data={customers}
                                                                                                                                                                                                                                          keyExtractor={(item) => item.id}
                                                                                                                                                                                                                                                      renderItem={({ item }) => (
                                                                                                                                                                                                                                                                    <View style={styles.card}>
                                                                                                                                                                                                                                                                                    <View>
                                                                                                                                                                                                                                                                                                      <Text style={styles.cardTitle}>{item.name}</Text>
                                                                                                                                                                                                                                                                                                                        <Text style={styles.cardSub}>{item.phone}</Text>
                                                                                                                                                                                                                                                                                                                                          <Text style={styles.balance}>Bakiye: ${item.balanceUSD}</Text>
                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                  {activeTab === 'stok' && (
                                                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.content}>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={styles.addBtn} onPress={() => setStokModalVisible(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.btnText}>+ Stok Ekle</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data={stock}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keyExtractor={(item) => item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderItem={({ item }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View style={styles.card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.cardTitle}>{item.name}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.cardSub}>Stok Adedi: {item.qty} adet</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.price}>${item.priceUSD}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Cari Modal */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Modal visible={cariModalVisible} animationType="slide" transparent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View style={styles.modalOverlay}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.modalContent}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Text style={styles.modalTitle}>Yeni Cari Ekle</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <TextInput style={styles.input} placeholder="Müşteri / Firma Adı" value={newCariName} onChangeText={setNewCariName} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <TextInput style={styles.input} placeholder="Telefon Numarası" value={newCariPhone} onChangeText={setNewCariPhone} keyboardType="phone-pad" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TouchableOpacity style={styles.addBtn} onPress={handleAddCari}><Text style={styles.btnText}>Kaydet</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <TouchableOpacity style={styles.cancelBtn} onPress={() => setCariModalVisible(false)}><Text>İptal</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Modal>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Stok Modal */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Modal visible={stokModalVisible} animationType="slide" transparent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <View style={styles.modalOverlay}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.modalContent}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.modalTitle}>Yeni Stok Ekle</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TextInput style={styles.input} placeholder="Ürün Adı" value={newStokName} onChangeText={setNewStokName} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TextInput style={styles.input} placeholder="Adet" value={newStokQty} onChangeText={setNewStokQty} keyboardType="numeric" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <TextInput style={styles.input} placeholder="Birim Fiyat ($)" value={newStokPrice} onChangeText={setNewStokPrice} keyboardType="numeric" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <TouchableOpacity style={styles.addBtn} onPress={handleAddStok}><Text style={styles.btnText}>Kaydet</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={styles.cancelBtn} onPress={() => setStokModalVisible(false)}><Text>İptal</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container: { flex: 1, backgroundColor: '#f8fafc', paddingTop: 40 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      header: { backgroundColor: '#0f172a', padding: 16, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headerTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tabBar: { flexDirection: 'row', backgroundColor: '#1e293b' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tab: { flex: 1, padding: 12, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              activeTab: { borderBottomWidth: 3, borderBottomColor: '#38bdf8' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tabText: { color: '#fff', fontWeight: '600' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  content: { flex: 1, padding: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    card: { backgroundColor: '#fff', padding: 14, borderRadius: 8, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#e2e8f0' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cardTitle: { fontSize: 15, fontWeight: 'bold', color: '#0f172a' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cardSub: { color: '#64748b', marginTop: 2, fontSize: 13 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          balance: { color: '#dc2626', fontWeight: 'bold', marginTop: 4 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price: { color: '#16a34a', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              addBtn: { backgroundColor: '#0284c7', padding: 12, borderRadius: 6, alignItems: 'center', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btnText: { color: '#fff', fontWeight: 'bold', fontSize: 13 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    modalContent: { backgroundColor: '#fff', padding: 20, borderRadius: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#0f172a' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input: { borderWidth: 1, borderColor: '#cbd5e1', padding: 10, borderRadius: 6, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cancelBtn: { alignItems: 'center', marginTop: 10, padding: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          